const { writeFile, existsSync, mkdirSync } = require("node:fs");
const path = require("node:path");
require("dotenv").config();
const args = process.argv.slice(2);
const envArg = args.find((a) => a.startsWith("--environment="));
const environment = envArg ? envArg.split("=")[1] : undefined;
const isProduction = environment === "prod";
const targetPath = "./projects/indem-clever/src/app/config/environment.ts";
const envDirectory = path.dirname(targetPath);
if (!existsSync(envDirectory)) mkdirSync(envDirectory, { recursive: true });
const apiBaseUrl = process.env["apiBaseUrl"] || "http://localhost:4202/api";
const content = 'export interface AppEnvironment { apiBaseUrl: string; production: boolean; }\nexport const environment: AppEnvironment = { apiBaseUrl: \'' + apiBaseUrl + '\', production: ' + isProduction + ' };\n';
writeFile(targetPath, content, (err) => { if (err) { console.error("Error: " + err); process.exit(1); } else { console.log("Generated " + targetPath); } });
